### ISSUE TITLE
Support for Verbb's Control Panel Nav

### ISSUE THREAD

**Issue by alexjcollins** [ethercreative/tags#4]
When installing the Tags plugin to a site with [Control Panel Nav](https://github.com/verbb/cp-nav) installed, a php error is thrown.

```
yii\base\ErrorException: Undefined offset: 10 in /Applications/MAMP/htdocs/.../vendor/ether/tags/src/TagManager.php:113
Stack trace:
#0 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/Applications/M...', 113)
#1 /Applications/MAMP/htdocs/.../vendor/ether/tags/src/TagManager.php(113): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/Applications/M...', 113, Array)
#2 [internal function]: ether\tagManager\TagManager->onRegisterCpNavItems(Object(craft\events\RegisterCpNavItemsEvent))
#3 /Applications/MAMP/htdocs/.../vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(craft\events\RegisterCpNavItemsEvent))
#4 /Applications/MAMP/htdocs/.../vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\twig\\...', 'registerCpNavIt...', Object(craft\events\RegisterCpNavItemsEvent))
#5 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/twig/variables/Cp.php(167): yii\base\Component->trigger('registerCpNavIt...', Object(craft\events\RegisterCpNavItemsEvent))
#6 /Applications/MAMP/htdocs/.../vendor/twig/twig/lib/Twig/Extension/Core.php(1619): craft\web\twig\variables\Cp->nav()
#7 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\web\twig\variables\Cp), 'nav', Array, 'method', false, false)
#8 /Applications/MAMP/htdocs/.../storage/runtime/compiled_templates/9a/9a6a3af8eb1bec4e1cc274cafa0649c9bacb1300a9810f3b9c219233d31bdeb7.php(194): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\web\twig\variables\Cp), 'nav', Array, 'method')
#9 /Applications/MAMP/htdocs/.../vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_f2321886c496f573fa54ae5df5818a7c1acd500294a909b2440fda05028e2b39->block_body(Array, Array)
#10 /Applications/MAMP/htdocs/.../storage/runtime/compiled_templates/5d/5d0ed0ec2cc85e9ac5e822fbff56e1dba99ea03cb3bc599dc7ec6e2545b29228.php(60): Twig_Template->displayBlock('body', Array, Array)
#11 /Applications/MAMP/htdocs/.../vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_968b2209959c38050f1d1e0eaad66a07b4d859b1e020d242bfddca5dd8163147->doDisplay(Array, Array)
#12 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#13 /Applications/MAMP/htdocs/.../vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#14 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#15 /Applications/MAMP/htdocs/.../storage/runtime/compiled_templates/0e/0e0ff154c18384c36af1a11588fcd47ff51ebc54e125a15249709b4f3735f1b6.php(40): craft\web\twig\Template->display(Array, Array)
#16 /Applications/MAMP/htdocs/.../vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_e311c154d5e65b560281186a0aba094bdc80bdf8c55889bc8132a45b6c697f36->doDisplay(Array, Array)
#17 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#18 /Applications/MAMP/htdocs/.../vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#19 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#20 /Applications/MAMP/htdocs/.../storage/runtime/compiled_templates/9a/9a6a3af8eb1bec4e1cc274cafa0649c9bacb1300a9810f3b9c219233d31bdeb7.php(94): craft\web\twig\Template->display(Array, Array)
#21 /Applications/MAMP/htdocs/.../vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_f2321886c496f573fa54ae5df5818a7c1acd500294a909b2440fda05028e2b39->doDisplay(Array, Array)
#22 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#23 /Applications/MAMP/htdocs/.../vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#24 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#25 /Applications/MAMP/htdocs/.../storage/runtime/compiled_templates/02/029748a5680fca6d133df9238d7b970ab4ba43ffa736672d4f5c847cc50157df.php(32): craft\web\twig\Template->display(Array, Array)
#26 /Applications/MAMP/htdocs/.../vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_c09e877a1c016e1c82ec3cd5f9b2465ec4d47befc5c21cb87b588f96aa177b77->doDisplay(Array, Array)
#27 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#28 /Applications/MAMP/htdocs/.../vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#29 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#30 /Applications/MAMP/htdocs/.../vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#31 /Applications/MAMP/htdocs/.../vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#32 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('dashboard/_inde...', Array)
#33 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/View.php(378): craft\web\View->renderTemplate('dashboard/_inde...', Array)
#34 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/Controller.php(155): craft\web\View->renderPageTemplate('dashboard/_inde...', Array)
#35 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/controllers/DashboardController.php(135): craft\web\Controller->renderTemplate('dashboard/_inde...', Array)
#36 [internal function]: craft\controllers\DashboardController->actionIndex()
#37 /Applications/MAMP/htdocs/.../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#38 /Applications/MAMP/htdocs/.../vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#39 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('index', Array)
#40 /Applications/MAMP/htdocs/.../vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#41 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('dashboard/index', Array)
#42 /Applications/MAMP/htdocs/.../vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#43 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#44 /Applications/MAMP/htdocs/.../vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#45 /Applications/MAMP/htdocs/.../web/index.php(21): yii\base\Application->run()
#46 {main}
```

**Comment by allampraveen** [comment]
use the fork site, which I created. it should fix the issue

**Comment by alexjcollins** [comment]
@allampraveen Nice one! Will check it out 👍
