### ISSUE TITLE
v1.0.1 Modal Crashes when pulling up replace with tag when deleting

### ISSUE THREAD

**Issue by neokoenig** [ethercreative/tags#5]
Steps to reproduce:

- Select a Tag to Delete
- Click Replace with Tag
- Following Modal popup crashes

PHP version | 7.2.1
MySQL 5.6.26
GD 7.2.1
Craft Pro 3.0.33

Stack trace:

```
2018-12-02 14:08:05 [-][1][-][error][yii\web\HttpException:400] yii\web\BadRequestHttpException: ether\tagManager\Elements\Tag doesn’t exist or doesn’t extend/implement craft\base\ElementInterface in /srv/www/REDACTED/public/vendor/craftcms/cms/src/controllers/BaseElementsController.php:64
Stack trace:
#0 /srv/www/REDACTED/public/vendor/craftcms/cms/src/controllers/ElementsController.php(44): craft\controllers\BaseElementsController->elementType()
#1 [internal function]: craft\controllers\ElementsController->actionGetModalBody()
#2 /srv/www/REDACTED/public/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /srv/www/REDACTED/public/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /srv/www/REDACTED/public/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('get-modal-body', Array)
#5 /srv/www/REDACTED/public/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-modal-body', Array)
#6 /srv/www/REDACTED/public/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('elements/get-mo...', Array)
#7 /srv/www/REDACTED/public/vendor/craftcms/cms/src/web/Application.php(542): craft\web\Application->runAction('elements/get-mo...', Array)
#8 /srv/www/REDACTED/public/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /srv/www/REDACTED/public/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /srv/www/REDACTED/public/web/index.php(21): yii\base\Application->run()
#11 {main}
2018-12-02 14:08:05 [-][1][-][info][application] $_GET = [
    'p' => 'admin/actions/elements/get-modal-body'
]

$_POST = [
    'context' => 'modal'
    'elementType' => 'ether\\tagManager\\Elements\\Tag'
    'sources' => ''
    'showSiteMenu' => '0'
]

$_FILES = []

$_COOKIE = [ etc]

$_SESSION = [ etc ]

$_SERVER = [
    'HTTP_HOST' => 'REDACTED'
    'HTTP_CONNECTION' => 'keep-alive'
    'CONTENT_LENGTH' => '85'
    'HTTP_ORIGIN' => 'http://REDACTED'
    'HTTP_X_CSRF_TOKEN' => 'REDACTED'
    'HTTP_X_REGISTERED_ASSET_BUNDLES' => ',ether\\tagManager\\web\\assets\\TagIndexAsset,craft\\web\\assets\\cp\\CpAsset,craft\\web\\assets\\d3\\D3Asset,craft\\web\\assets\\elementresizedetector\\ElementResizeDetectorAsset,craft\\web\\assets\\garnish\\GarnishAsset,yii\\web\\JqueryAsset,craft\\web\\assets\\jquerytouchevents\\JqueryTouchEventsAsset,craft\\web\\assets\\velocity\\VelocityAsset,craft\\web\\assets\\jqueryui\\JqueryUiAsset,craft\\web\\assets\\jquerypayment\\JqueryPaymentAsset,craft\\web\\assets\\datepickeri18n\\DatepickerI18nAsset,craft\\web\\assets\\picturefill\\PicturefillAsset,craft\\web\\assets\\selectize\\SelectizeAsset,craft\\web\\assets\\fileupload\\FileUploadAsset,craft\\web\\assets\\xregexp\\XregexpAsset,craft\\web\\assets\\fabric\\FabricAsset'
    'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8'
    'HTTP_X_REGISTERED_JS_FILES' => ',http://REDACTED/cpresources/987ca07f/d3.js?v=1543420452,http://REDACTED/cpresources/35e3175c/element-resize-detector.js?v=1543420452,http://REDACTED/cpresources/1a73bca9/jquery.js?v=1543420452,http://REDACTED/cpresources/917dbcec/jquery.mobile-events.min.js?v=1543420452,http://REDACTED/cpresources/bfc4bd4/velocity.js?v=1543420452,http://REDACTED/cpresources/abc1b7f9/garnish.js?v=1543420452,http://REDACTED/cpresources/4555d071/jquery-ui.min.js?v=1543420452,http://REDACTED/cpresources/17dbe43c/jquery.payment.js?v=1543420452,http://REDACTED/cpresources/db040ab6/datepicker-en-GB.js?v=1543420458,http://REDACTED/cpresources/96d9802e/picturefill.js?v=1543420452,http://REDACTED/cpresources/c2a7adaa/selectize.js?v=1543420452,http://REDACTED/cpresources/8e3181d0/jquery.fileupload.js?v=1543420452,http://REDACTED/cpresources/c8cbe920/xregexp-all.js?v=1543420452,http://REDACTED/cpresources/be8763c7/fabric.js?v=1543420452,http://REDACTED/cpresources/c48888e3/js/Craft.min.js?v=1543420452,http://REDACTED/cpresources/791fef67/TagIndex.js?v=1543759600'
    'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01'
    'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36'
    'HTTP_DNT' => '1'
    'HTTP_REFERER' => 'http://REDACTED/admin/tags'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate'
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9'
    'HTTP_COOKIE' => 'REDACTED'
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    'SERVER_SIGNATURE' => ''
    'SERVER_SOFTWARE' => 'Apache'
    'SERVER_NAME' => 'REDACTED'
    'SERVER_ADDR' => 'REDACTED'
    'SERVER_PORT' => '80'
    'REMOTE_ADDR' => 'REDACTED'
    'DOCUMENT_ROOT' => '/srv/www/REDACTED/public/web/'
    'REQUEST_SCHEME' => 'http'
    'CONTEXT_PREFIX' => ''
    'CONTEXT_DOCUMENT_ROOT' => '/srv/www/REDACTED/public/web/'
    'SERVER_ADMIN' => 'webmaster@REDACTED'
    'SCRIPT_FILENAME' => '/srv/www/REDACTED/public/web/index.php'
    'REMOTE_PORT' => '60799'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'REQUEST_METHOD' => 'POST'
    'QUERY_STRING' => 'p=admin/actions/elements/get-modal-body'
    'REQUEST_URI' => '/index.php?p=admin/actions/elements/get-modal-body'
    'SCRIPT_NAME' => '/index.php'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1543759685.571
    'REQUEST_TIME' => 1543759685
    'ENVIRONMENT' => 'staging'
    'SECURITY_KEY' => 'REDACTED'
    'DB_DRIVER' => 'mysql'
    'DB_SERVER' => 'localhost'
    'DB_USER' => 'REDACTED'
    'DB_PASSWORD' => 'REDACTED'
    'DB_DATABASE' => 'REDACTED'
    'DB_SCHEMA' => 'public'
    'DB_TABLE_PREFIX' => ''
    'DB_PORT' => '3306'
]
```

**Comment by jwmatlock** [comment]
Experiencing the same issue with Craft CMS 3.0.25.

**Comment by auralon** [comment]
Experiencing the same issue with Craft CMS `3.0.40` too.

**Comment by mafu-d** [comment]
Same here, on Craft CMS 3.0.37.

**Comment by migswd** [comment]
Same bug with Craft CMS 3.1.19

**Comment by Tam** [comment]
Do you have any other plugins installed? I've just tested on a fresh Craft install (3.1.20.1) without issue.

**Comment by migswd** [comment]
I got Craft last version.
And yes of course I got plenty of other plugins :).

What info do you need so we can understand the bug?

**Comment by Tam** [comment]
@migswd A list of the other plugins you're using. It's likely that one is interfering with Tags in some way which is causing the issue.

**Comment by migswd** [comment]
OK here is the list :

=============            
Activeusers
1.1.1
A widget showing active users

Documentation

Installed	
Analytics
4.0.7
Customizable statistics widgets and entry tracking for Google Analytics.

Documentation
Settings
 

Installed	
CP Element Count
1.1.0
Adds an element count to sections, categories, user groups and asset folders in the Craft control panel

Documentation

Installed	
Campaign
1.7.3
Send and manage email campaigns, contacts and mailing lists.

Documentation
Settings
 

Installed	
Content Stats
2.1.0
Display info about your site's entries, categories, users, and assets.

Documentation

Installed	
Embedded Assets
2.0.2
Manage YouTube videos, Instagram photos, Twitter posts and more as first class assets

Documentation
Settings

Installed	
Entry Count
2.0.2
Counts and displays the number of times that an entry has been viewed.

Documentation
Settings

Installed	
Enupal Backup
1.2.6
Fully integrated Backup solution for Craft CMS

Documentation
Settings
 

Installed	
Help Links
1.0.7
Define useful links to be added to the dashboard for clients.

Documentation
Settings

Installed	
Image Resizer
2.0.4
Image Resizer resizes your assets when they are uploaded.

Documentation
Settings

Installed	
Linkit
1.1.10
One link field to rule them all.

Documentation

4FCD-UIW0-V9NO-A9QI-H8ZM-Z2C0
Installed	
Outpost
1.1.1
Debug plugin to track and gain insights on requests to your Craft site

Documentation
Settings

Installed	
Postmark
2.0.1
Postmark adapter for Craft CMS

Documentation

Installed	
Redactor
2.3.2
Edit rich text content in Craft CMS using Redactor by Imperavi.

Documentation

Installed	
Related
1.0.0
A simple plugin that adds a widget within the Craft CP page sidebar, allowing you to quickly and easily access related entries.

Documentation
Settings

Installed	
SEOmatic
3.1.46
SEOmatic facilitates modern SEO best practices & implementation for Craft CMS 3. It is a turnkey SEO system that is comprehensive, powerful, and flexible.

Documentation
Settings
 

Installed	
Social
2.0.0
Let your visitors log into Craft with web services like Facebook, Google, Twitter…

Documentation
Settings
 

Installed	
Splashing Images
1.2.0
unsplash.com integration for Craft 3

Documentation
Settings

Installed	
Star Ratings
2.1.1
An easy to use and highly flexible ratings system.

Documentation
Settings
 

Installed	
Super Table
2.1.16
Super-charge your Craft workflow with Super Table. Use it to group fields together or build complex Matrix-in-Matrix solutions.

Documentation
Settings

Installed	
Support
1.0.0
Simple support system for tracking, prioritising and solving customer support tickets.

Documentation
Settings

Installed	
Tags
1.0.2
A tag manager for Craft 3

Documentation

Installed	
Upvote
2.0.3
Lets your users upvote/downvote, "like", or favorite any type of element.

Documentation
Settings
 

Installed	
Videos
2.0.6
Connect to YouTube & Vimeo and publish social videos on your website.

Documentation
Settings
 

Installed	
Wishlist
1.0.6
Allow users to create lists to store favourite entries, save products in a wishlist and more.

Documentation
Settings
 

Installed	
Algolia
2.0.0
Easily pull search results from Algolia into your Craft CMS website

Documentation

Disabled	
Collapse CP Nav
1.0.0
Hide the control panel’s left pane navigation to free up more screen real estate.

Documentation
 

Disabled	
Do It Yourself widget
2.0.1
Do It Yourself widget for Craft CMS

Documentation

Disabled	
Element Lists
2.0.0
Simple Element lists

Documentation
 

Disabled	
Migration Assistant
3.1.0.1
Create migrations for settings and content at the click of a mouse. Keep environments in sync with ease.

Documentation
 

Disabled	
Similar
1.0.5
Similar for Craft lets you find elements, Entries, Categories, Commerce Products, etc, that are similar, based on... other related elements.

Documentation

Disabled	
View Count
1.0.0
Count the number of times an element has been viewed.

Documentation
 

Disabled	
oEmbed
1.1.3
A simple plugin to extract media information from websites, like youtube videos, twitter statuses or blog articles.

Documentation

Disabled	
Communicator
1.0.0
Widgets that provide content to several users from a single source.

Documentation

**Comment by jurriaanr** [comment]
I have the same issue. I compared my plugins with the ones above and the there are 3 overlapping. One of them is Embedded Assets, which i disabled. That fixed the problem. I do need the embedded assets plugin, so a fix would be great!

On a side note - and I can make a separate issue if you wish. When editing a single tag and deleting it, the replace window is not triggered and the tag is removed as is. I would expect the same functionality there.

**Comment by Tam** [comment]
I can't recreate the issue with the Embedded Assets plugin, it's possible they pushed a release that fixed it. Is it still an issue for you?

@jurriaanr I've just released 1.0.3 which adds the replace modal to the edit page delete action.

**Comment by jurriaanr** [comment]
The problems seems to have been partly solved. There is no longer a crash and I get the popup. However, in the popup the All Tags option does not show any tags, nor can I actually select a tag

![Tags](https://user-images.githubusercontent.com/7426848/58961517-988b4e80-87a9-11e9-8f54-3d348b6ca3a8.gif)

**Comment by mattandrews** [comment]
I'm experiencing this issue too and don't have the Embedded Assets plugin installed. Here are my plugins:

```
Amazon S3	        1.1.3
Control Panel CSS	2.1.0
Control Panel JS	2.1.0
Element API	        2.5.4
Element Map	        1.2.1
Inventory               2.0.2
Preview Button          1.0.3
Recentchanges           1.1.2
Redactor                2.3.1
Super Table	        2.1.8
Tags	                1.0.1
```

Using Craft Pro 3.1.12 and I haven't tried v1.0.3 suggested here yet (since it sounds like it doesn't fix the issue?)
